// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	context "context"

	repositories "github.com/quocbang/grpc-gateway/server/repositories"
	mock "github.com/stretchr/testify/mock"
)

// Account is an autogenerated mock type for the Account type
type Account struct {
	mock.Mock
}

type Account_Expecter struct {
	mock *mock.Mock
}

func (_m *Account) EXPECT() *Account_Expecter {
	return &Account_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: _a0, _a1
func (_m *Account) CreateAccount(_a0 context.Context, _a1 repositories.CreateAccountRequest) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.CreateAccountRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Account_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type Account_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repositories.CreateAccountRequest
func (_e *Account_Expecter) CreateAccount(_a0 interface{}, _a1 interface{}) *Account_CreateAccount_Call {
	return &Account_CreateAccount_Call{Call: _e.mock.On("CreateAccount", _a0, _a1)}
}

func (_c *Account_CreateAccount_Call) Run(run func(_a0 context.Context, _a1 repositories.CreateAccountRequest)) *Account_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositories.CreateAccountRequest))
	})
	return _c
}

func (_c *Account_CreateAccount_Call) Return(_a0 error) *Account_CreateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Account_CreateAccount_Call) RunAndReturn(run func(context.Context, repositories.CreateAccountRequest) error) *Account_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVerifyAccount provides a mock function with given fields: _a0, _a1
func (_m *Account) CreateVerifyAccount(_a0 context.Context, _a1 repositories.CreateVerifyAccountRequest) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.CreateVerifyAccountRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Account_CreateVerifyAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVerifyAccount'
type Account_CreateVerifyAccount_Call struct {
	*mock.Call
}

// CreateVerifyAccount is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repositories.CreateVerifyAccountRequest
func (_e *Account_Expecter) CreateVerifyAccount(_a0 interface{}, _a1 interface{}) *Account_CreateVerifyAccount_Call {
	return &Account_CreateVerifyAccount_Call{Call: _e.mock.On("CreateVerifyAccount", _a0, _a1)}
}

func (_c *Account_CreateVerifyAccount_Call) Run(run func(_a0 context.Context, _a1 repositories.CreateVerifyAccountRequest)) *Account_CreateVerifyAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositories.CreateVerifyAccountRequest))
	})
	return _c
}

func (_c *Account_CreateVerifyAccount_Call) Return(_a0 error) *Account_CreateVerifyAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Account_CreateVerifyAccount_Call) RunAndReturn(run func(context.Context, repositories.CreateVerifyAccountRequest) error) *Account_CreateVerifyAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: _a0, _a1
func (_m *Account) GetAccount(_a0 context.Context, _a1 repositories.GetAccountRequest) (repositories.GetAccountReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 repositories.GetAccountReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.GetAccountRequest) (repositories.GetAccountReply, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repositories.GetAccountRequest) repositories.GetAccountReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(repositories.GetAccountReply)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repositories.GetAccountRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Account_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type Account_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repositories.GetAccountRequest
func (_e *Account_Expecter) GetAccount(_a0 interface{}, _a1 interface{}) *Account_GetAccount_Call {
	return &Account_GetAccount_Call{Call: _e.mock.On("GetAccount", _a0, _a1)}
}

func (_c *Account_GetAccount_Call) Run(run func(_a0 context.Context, _a1 repositories.GetAccountRequest)) *Account_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositories.GetAccountRequest))
	})
	return _c
}

func (_c *Account_GetAccount_Call) Return(_a0 repositories.GetAccountReply, _a1 error) *Account_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Account_GetAccount_Call) RunAndReturn(run func(context.Context, repositories.GetAccountRequest) (repositories.GetAccountReply, error)) *Account_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetVerifyAccount provides a mock function with given fields: _a0, _a1
func (_m *Account) GetVerifyAccount(_a0 context.Context, _a1 repositories.GetVerifyAccountRequest) (repositories.GetVerifyAccountReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 repositories.GetVerifyAccountReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.GetVerifyAccountRequest) (repositories.GetVerifyAccountReply, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repositories.GetVerifyAccountRequest) repositories.GetVerifyAccountReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(repositories.GetVerifyAccountReply)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repositories.GetVerifyAccountRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Account_GetVerifyAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVerifyAccount'
type Account_GetVerifyAccount_Call struct {
	*mock.Call
}

// GetVerifyAccount is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repositories.GetVerifyAccountRequest
func (_e *Account_Expecter) GetVerifyAccount(_a0 interface{}, _a1 interface{}) *Account_GetVerifyAccount_Call {
	return &Account_GetVerifyAccount_Call{Call: _e.mock.On("GetVerifyAccount", _a0, _a1)}
}

func (_c *Account_GetVerifyAccount_Call) Run(run func(_a0 context.Context, _a1 repositories.GetVerifyAccountRequest)) *Account_GetVerifyAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositories.GetVerifyAccountRequest))
	})
	return _c
}

func (_c *Account_GetVerifyAccount_Call) Return(_a0 repositories.GetVerifyAccountReply, _a1 error) *Account_GetVerifyAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Account_GetVerifyAccount_Call) RunAndReturn(run func(context.Context, repositories.GetVerifyAccountRequest) (repositories.GetVerifyAccountReply, error)) *Account_GetVerifyAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *Account) Login(_a0 context.Context, _a1 repositories.LoginRequest) (repositories.LoginReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 repositories.LoginReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.LoginRequest) (repositories.LoginReply, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repositories.LoginRequest) repositories.LoginReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(repositories.LoginReply)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repositories.LoginRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Account_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Account_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 repositories.LoginRequest
func (_e *Account_Expecter) Login(_a0 interface{}, _a1 interface{}) *Account_Login_Call {
	return &Account_Login_Call{Call: _e.mock.On("Login", _a0, _a1)}
}

func (_c *Account_Login_Call) Run(run func(_a0 context.Context, _a1 repositories.LoginRequest)) *Account_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositories.LoginRequest))
	})
	return _c
}

func (_c *Account_Login_Call) Return(_a0 repositories.LoginReply, _a1 error) *Account_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Account_Login_Call) RunAndReturn(run func(context.Context, repositories.LoginRequest) (repositories.LoginReply, error)) *Account_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccount creates a new instance of Account. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccount(t interface {
	mock.TestingT
	Cleanup(func())
}) *Account {
	mock := &Account{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
